// <auto-generated />
using System;
using MHRS.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MHRS.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20251219080702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MHRS.Model.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointmentDate");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit")
                        .HasColumnName("isDone");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("MHRS.Model.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cityName");

                    b.HasKey("CityId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "İstanbul"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Ankara"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "İzmir"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Bursa"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Antalya"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Tekirdağ"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Gaziantep"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Konya"
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Kayseri"
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Diyarbakır"
                        });
                });

            modelBuilder.Entity("MHRS.Model.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hospitalId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("cityId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hospitalName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("HospitalId");

                    b.HasIndex("CityId");

                    b.ToTable("hospitals");

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            Address = "İstanbul, Kadıköy",
                            CityId = 1,
                            Description = "Modern veteriner hastanesi",
                            HospitalName = "Acibadem Veteriner Hastanesi",
                            Phone = "0212-555-0001"
                        },
                        new
                        {
                            HospitalId = 2,
                            Address = "İstanbul, Nişantaşı",
                            CityId = 1,
                            Description = "Uluslararası standartlarda hizmet",
                            HospitalName = "American Hospital Vet",
                            Phone = "0212-555-0002"
                        },
                        new
                        {
                            HospitalId = 3,
                            Address = "Ankara, Keçiören",
                            CityId = 2,
                            Description = "Ankara'nın en iyi veteriner merkezi",
                            HospitalName = "Ankara Veteriner Merkezi",
                            Phone = "0312-555-0001"
                        },
                        new
                        {
                            HospitalId = 4,
                            Address = "İzmir, Alsancak",
                            CityId = 3,
                            Description = "Evcil hayvanlar için özel hizmetler",
                            HospitalName = "İzmir Pet Hospital",
                            Phone = "0232-555-0001"
                        },
                        new
                        {
                            HospitalId = 5,
                            Address = "Tekirdağ, Merkez",
                            CityId = 6,
                            Description = "Tekirdağ'da güvenilir veteriner hizmeti",
                            HospitalName = "Tekirdağ Vet Kliniği",
                            Phone = "0282-555-0001"
                        });
                });

            modelBuilder.Entity("MHRS.Model.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mobileNo");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("patientName");

                    b.HasKey("PatientId");

                    b.ToTable("patient");
                });

            modelBuilder.Entity("MHRS.Model.Appointment", b =>
                {
                    b.HasOne("MHRS.Model.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MHRS.Model.Hospital", b =>
                {
                    b.HasOne("MHRS.Model.City", "City")
                        .WithMany("Hospitals")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MHRS.Model.City", b =>
                {
                    b.Navigation("Hospitals");
                });
#pragma warning restore 612, 618
        }
    }
}
