// <auto-generated />
using System;
using MHRS.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MHRS.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    partial class AppointmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MHRS.Model.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointmentDate");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int")
                        .HasColumnName("hospitalId");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit")
                        .HasColumnName("isDone");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("MHRS.Model.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cityName");

                    b.HasKey("CityId");

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Adana"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Adıyaman"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Afyonkarahisar"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Ağrı"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Amasya"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Ankara"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Antalya"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Artvin"
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Aydın"
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Balıkesir"
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Bilecik"
                        },
                        new
                        {
                            CityId = 12,
                            CityName = "Bingöl"
                        },
                        new
                        {
                            CityId = 13,
                            CityName = "Bitlis"
                        },
                        new
                        {
                            CityId = 14,
                            CityName = "Bolu"
                        },
                        new
                        {
                            CityId = 15,
                            CityName = "Burdur"
                        },
                        new
                        {
                            CityId = 16,
                            CityName = "Bursa"
                        },
                        new
                        {
                            CityId = 17,
                            CityName = "Çanakkale"
                        },
                        new
                        {
                            CityId = 18,
                            CityName = "Çankırı"
                        },
                        new
                        {
                            CityId = 19,
                            CityName = "Çorum"
                        },
                        new
                        {
                            CityId = 20,
                            CityName = "Denizli"
                        },
                        new
                        {
                            CityId = 21,
                            CityName = "Diyarbakır"
                        },
                        new
                        {
                            CityId = 22,
                            CityName = "Edirne"
                        },
                        new
                        {
                            CityId = 23,
                            CityName = "Elazığ"
                        },
                        new
                        {
                            CityId = 24,
                            CityName = "Erzincan"
                        },
                        new
                        {
                            CityId = 25,
                            CityName = "Erzurum"
                        },
                        new
                        {
                            CityId = 26,
                            CityName = "Eskişehir"
                        },
                        new
                        {
                            CityId = 27,
                            CityName = "Gaziantep"
                        },
                        new
                        {
                            CityId = 28,
                            CityName = "Giresun"
                        },
                        new
                        {
                            CityId = 29,
                            CityName = "Gümüşhane"
                        },
                        new
                        {
                            CityId = 30,
                            CityName = "Hakkari"
                        },
                        new
                        {
                            CityId = 31,
                            CityName = "Hatay"
                        },
                        new
                        {
                            CityId = 32,
                            CityName = "Isparta"
                        },
                        new
                        {
                            CityId = 33,
                            CityName = "Mersin"
                        },
                        new
                        {
                            CityId = 34,
                            CityName = "İstanbul"
                        },
                        new
                        {
                            CityId = 35,
                            CityName = "İzmir"
                        },
                        new
                        {
                            CityId = 36,
                            CityName = "Kars"
                        },
                        new
                        {
                            CityId = 37,
                            CityName = "Kastamonu"
                        },
                        new
                        {
                            CityId = 38,
                            CityName = "Kayseri"
                        },
                        new
                        {
                            CityId = 39,
                            CityName = "Kırklareli"
                        },
                        new
                        {
                            CityId = 40,
                            CityName = "Kırşehir"
                        },
                        new
                        {
                            CityId = 41,
                            CityName = "Kocaeli"
                        },
                        new
                        {
                            CityId = 42,
                            CityName = "Konya"
                        },
                        new
                        {
                            CityId = 43,
                            CityName = "Kütahya"
                        },
                        new
                        {
                            CityId = 44,
                            CityName = "Malatya"
                        },
                        new
                        {
                            CityId = 45,
                            CityName = "Manisa"
                        },
                        new
                        {
                            CityId = 46,
                            CityName = "Kahramanmaraş"
                        },
                        new
                        {
                            CityId = 47,
                            CityName = "Mardin"
                        },
                        new
                        {
                            CityId = 48,
                            CityName = "Muğla"
                        },
                        new
                        {
                            CityId = 49,
                            CityName = "Muş"
                        },
                        new
                        {
                            CityId = 50,
                            CityName = "Nevşehir"
                        },
                        new
                        {
                            CityId = 51,
                            CityName = "Niğde"
                        },
                        new
                        {
                            CityId = 52,
                            CityName = "Ordu"
                        },
                        new
                        {
                            CityId = 53,
                            CityName = "Rize"
                        },
                        new
                        {
                            CityId = 54,
                            CityName = "Sakarya"
                        },
                        new
                        {
                            CityId = 55,
                            CityName = "Samsun"
                        },
                        new
                        {
                            CityId = 56,
                            CityName = "Siirt"
                        },
                        new
                        {
                            CityId = 57,
                            CityName = "Sinop"
                        },
                        new
                        {
                            CityId = 58,
                            CityName = "Sivas"
                        },
                        new
                        {
                            CityId = 59,
                            CityName = "Tekirdağ"
                        },
                        new
                        {
                            CityId = 60,
                            CityName = "Tokat"
                        },
                        new
                        {
                            CityId = 61,
                            CityName = "Trabzon"
                        },
                        new
                        {
                            CityId = 62,
                            CityName = "Tunceli"
                        },
                        new
                        {
                            CityId = 63,
                            CityName = "Şanlıurfa"
                        },
                        new
                        {
                            CityId = 64,
                            CityName = "Uşak"
                        },
                        new
                        {
                            CityId = 65,
                            CityName = "Van"
                        },
                        new
                        {
                            CityId = 66,
                            CityName = "Yozgat"
                        },
                        new
                        {
                            CityId = 67,
                            CityName = "Zonguldak"
                        },
                        new
                        {
                            CityId = 68,
                            CityName = "Aksaray"
                        },
                        new
                        {
                            CityId = 69,
                            CityName = "Bayburt"
                        },
                        new
                        {
                            CityId = 70,
                            CityName = "Karaman"
                        },
                        new
                        {
                            CityId = 71,
                            CityName = "Kırıkkale"
                        },
                        new
                        {
                            CityId = 72,
                            CityName = "Batman"
                        },
                        new
                        {
                            CityId = 73,
                            CityName = "Şırnak"
                        },
                        new
                        {
                            CityId = 74,
                            CityName = "Bartın"
                        },
                        new
                        {
                            CityId = 75,
                            CityName = "Ardahan"
                        },
                        new
                        {
                            CityId = 76,
                            CityName = "Iğdır"
                        },
                        new
                        {
                            CityId = 77,
                            CityName = "Yalova"
                        },
                        new
                        {
                            CityId = 78,
                            CityName = "Karabük"
                        },
                        new
                        {
                            CityId = 79,
                            CityName = "Kilis"
                        },
                        new
                        {
                            CityId = 80,
                            CityName = "Osmaniye"
                        },
                        new
                        {
                            CityId = 81,
                            CityName = "Düzce"
                        });
                });

            modelBuilder.Entity("MHRS.Model.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hospitalId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("cityId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("hospitalName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("HospitalId");

                    b.HasIndex("CityId");

                    b.ToTable("hospitals", (string)null);

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            Address = "İstanbul, Kadıköy",
                            CityId = 34,
                            Description = "Modern veteriner hastanesi",
                            HospitalName = "Acibadem Veteriner Hastanesi",
                            Phone = "0212-555-0001"
                        },
                        new
                        {
                            HospitalId = 2,
                            Address = "İstanbul, Nişantaşı",
                            CityId = 34,
                            Description = "Uluslararası standartlarda hizmet",
                            HospitalName = "American Hospital Vet",
                            Phone = "0212-555-0002"
                        },
                        new
                        {
                            HospitalId = 3,
                            Address = "Ankara, Keçiören",
                            CityId = 6,
                            Description = "Ankara'nın en iyi veteriner merkezi",
                            HospitalName = "Ankara Veteriner Merkezi",
                            Phone = "0312-555-0001"
                        },
                        new
                        {
                            HospitalId = 4,
                            Address = "İzmir, Alsancak",
                            CityId = 35,
                            Description = "Evcil hayvanlar için özel hizmetler",
                            HospitalName = "İzmir Pet Hospital",
                            Phone = "0232-555-0001"
                        },
                        new
                        {
                            HospitalId = 5,
                            Address = "Tekirdağ, Merkez",
                            CityId = 59,
                            Description = "Tekirdağ'da güvenilir veteriner hizmeti",
                            HospitalName = "Tekirdağ Vet Kliniği",
                            Phone = "0282-555-0001"
                        });
                });

            modelBuilder.Entity("MHRS.Model.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("patientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("mobileNo");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("patientName");

                    b.HasKey("PatientId");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("MHRS.Model.Appointment", b =>
                {
                    b.HasOne("MHRS.Model.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MHRS.Model.Hospital", b =>
                {
                    b.HasOne("MHRS.Model.City", "City")
                        .WithMany("Hospitals")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MHRS.Model.City", b =>
                {
                    b.Navigation("Hospitals");
                });
#pragma warning restore 612, 618
        }
    }
}
